version: '1'

services:
  nginx1:
    restart: always
      #    depends_on:
      #      - grafana
    container_name: nginx1
    build: ./nginx1/
    ports:
      - "8001:8001"
    networks:
      - nginx1

  nginx2:
    restart: always
      #    depends_on:
      #      - grafana
    container_name: nginx2
    build: 
      context: ./nginx2/
    ports:
      - "8002:8002"
    networks:
      - nginx2

        #  grafana:
        #    image: grafana/grafana:latest
        #    restart: unless-stopped
        #    container_name: grafana
        #    ports:
        #      - "3000:3000"    
        #    networks:
        #      - nginx1
        #      - nginx2

networks:
  nginx1:
  nginx2:
